name: Pylint

on:
  push:
    branches: [dev, main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
# pip install pylint
#     - name: Analysing the code with pylint
#       run: |
#         pylint `ls -R|grep .py$|xargs`
    - name: Python Linter
      #uses: sunnysid3up/python-linter@v0.1-beta.7
      uses: ricardochaves/python-lint@v1.4.0
  

